version: '3'

networks:
  ns-corp:
    driver: bridge

services:

  ns-client:
    container_name: ns-client
    networks:
      - ns-corp
    image: nginx:latest
    restart: always
    volumes:
      - ./dist/apps/client:/var/www/apps/client
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - ns-api-auth
      - ns-api-portal
      - ns-api-objects
      - ns-api-socket
    command: ng serve client

  ns-api-auth:
    container_name: ns-api-auth
    networks:
      - ns-corp
    image: ns-api-auth
    build: ./apps
    restart: always
    volumes:
      - ./apps/api-auth:/usr/src/apps/api-auth
    ports:
      - 3000:3000
    depends_on:
      - ns-mariadb
    command: ng serve api-auth

  ns-api-portal:
    container_name: ns-api-portal
    networks:
      - ns-corp
    image: ns-api-portal
    build: ./apps
    restart: always
    volumes:
      - ./apps/api-portal:/usr/src/apps/api-portal
    ports:
      - 3001:3001
    depends_on:
      - ns-mariadb
    command: ng serve api-portal

  ns-api-objects:
    container_name: ns-api-objects
    networks:
      - ns-corp
    image: ns-api-objects
    build: ./apps
    restart: always
    volumes:
      - ./apps/api-objects:/usr/src/apps/api-objects
    ports:
      - 3003:3003
    depends_on:
      - ns-mariadb
    command: ng serve api-objects

  ns-api-socket:
    container_name: ns-api-socket
    networks:
      - ns-corp
    image: ns-api-socket
    build: ./apps
    restart: always
    volumes:
      - ./apps/api-socket:/usr/src/apps/api-socket
    ports:
      - 3002:3002
    depends_on:
      - ns-mariadb
    command: ng serve api-socket

  ns-mariadb:
    container_name: ns-mariadb
    networks:
      - ns-corp
    image: mariadb
    restart: always
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: neareststars
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    container_name: phpmyadmin
    networks:
      - ns-corp
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: ns-mariadb
      PMA_PORT: 3306
    restart: always
    ports:
     - 8080:80
    volumes:
     - /sessions
