### GET cat list

GET http://localhost:3000/category

### CREATE cat

POST http://localhost:3000/category

### GET single cat by id

GET http://localhost:3000/category/1


### UPDATE single cat by id

PUT http://localhost:3000/category/1

### DELETE single cat by id

DELETE http://localhost:3000/category/1
