### GET article list

GET http://localhost:3000/article

### CREATE article

POST http://localhost:3000/article

### GET single article by id

GET http://localhost:3000/article/1


### UPDATE single article by id

PUT http://localhost:3000/article/1

### DELETE single article by id

DELETE http://localhost:3000/article/1
